version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-recados
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend-recados
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html